// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKOH8BsUVGxdQVJIAPjWtwY0Q_tyyS-lE',
    appId: '1:940604271988:web:62fcedcd0235cba154d021',
    messagingSenderId: '940604271988',
    projectId: 'rastaurant-manager-57c8b',
    authDomain: 'rastaurant-manager-57c8b.firebaseapp.com',
    storageBucket: 'rastaurant-manager-57c8b.firebasestorage.app',
    measurementId: 'G-RJVBLCWJ2H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4Fgr6JN-KoxEIULHiSSZHSdtVdEP5Ih8',
    appId: '1:940604271988:android:04690675b7e3ab5354d021',
    messagingSenderId: '940604271988',
    projectId: 'rastaurant-manager-57c8b',
    storageBucket: 'rastaurant-manager-57c8b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_rTRem7APsUjnB-YC-YTADV0MFNT7KpQ',
    appId: '1:940604271988:ios:a55c82fb76c1ad6254d021',
    messagingSenderId: '940604271988',
    projectId: 'rastaurant-manager-57c8b',
    storageBucket: 'rastaurant-manager-57c8b.firebasestorage.app',
    iosBundleId: 'com.example.restaurantManagement',
  );

}